// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABL9ICtM91hy97yCsGdHhbRRzkBrsEnFs',
    appId: '1:586761692623:web:f76a42feff35bad1f19eba',
    messagingSenderId: '586761692623',
    projectId: 'internship-task-dc378',
    authDomain: 'internship-task-dc378.firebaseapp.com',
    storageBucket: 'internship-task-dc378.firebasestorage.app',
    measurementId: 'G-ZYL9J5Z65F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8N3uhsU6XD-bnR7717Tf7TThukBch8MQ',
    appId: '1:586761692623:android:609b1a5baec7f708f19eba',
    messagingSenderId: '586761692623',
    projectId: 'internship-task-dc378',
    storageBucket: 'internship-task-dc378.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEdQ30M44iwRBJNoSm-gBLa0euVSMRmrM',
    appId: '1:586761692623:ios:065663879a104a11f19eba',
    messagingSenderId: '586761692623',
    projectId: 'internship-task-dc378',
    storageBucket: 'internship-task-dc378.firebasestorage.app',
    iosBundleId: 'com.example.internSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEdQ30M44iwRBJNoSm-gBLa0euVSMRmrM',
    appId: '1:586761692623:ios:065663879a104a11f19eba',
    messagingSenderId: '586761692623',
    projectId: 'internship-task-dc378',
    storageBucket: 'internship-task-dc378.firebasestorage.app',
    iosBundleId: 'com.example.internSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABL9ICtM91hy97yCsGdHhbRRzkBrsEnFs',
    appId: '1:586761692623:web:8116755502e91747f19eba',
    messagingSenderId: '586761692623',
    projectId: 'internship-task-dc378',
    authDomain: 'internship-task-dc378.firebaseapp.com',
    storageBucket: 'internship-task-dc378.firebasestorage.app',
    measurementId: 'G-K930V9NEZH',
  );
}
